apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-admin
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kong.service.adminHttpPort }}
      targetPort: {{ .Values.kong.service.adminHttpPort }}
      protocol: TCP
      name: http-admin
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: server
    {{- include "gateway.selectorLabels" . | nindent 4 }}
