name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: tests/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        with:
          install_local_path_provisioner: true
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: tests/ct.yaml
  release:
    needs: lint-test
    environment: default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # See https://github.com/helm/chart-releaser-action/issues/6
      - name: Install Helm
        run: |
          curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm repo add gitlab    https://charts.gitlab.io/
          helm repo add bitnami   https://charts.bitnami.com/bitnami
          helm repo add stable    https://charts.helm.sh/stable
          helm repo add fulllearn https://fulllearn.duckdns.org/charts
          helm repo update

      - name: Add dependency chart repos
        run: |
          helm repo add fulllearn https://fulllearn.duckdns.org/charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
